name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0 0 * * *"

jobs:

  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
          bundler-cache: true

      - name: Build Site
        uses: helaili/jekyll-action@2.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          #pre_build_commands: 'bundle update ffi'
          #pre_build_commands: 'bundle install sassc'

        # run: bundle exec jekyll build
